# Generated by Django 4.2.29 on 2026-03-27 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50, unique=True, verbose_name='顧客ID')),
                ('name', models.CharField(max_length=200, verbose_name='顧客名')),
                ('attribute', models.CharField(choices=[('corporate', '法人'), ('individual', '個人'), ('government', '自治体')], default='corporate', max_length=20, verbose_name='属性')),
                ('corporate_number', models.CharField(blank=True, max_length=13, verbose_name='法人番号')),
                ('industry', models.CharField(blank=True, choices=[('it', 'IT・通信'), ('manufacturing', '製造業'), ('medical', '医療・福祉'), ('construction', '建設・不動産'), ('retail', '小売・流通'), ('finance', '金融・保険'), ('education', '教育・研究'), ('government', '行政・自治体'), ('agriculture', '農業・水産'), ('other', 'その他')], max_length=50, verbose_name='業種')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='メールアドレス')),
                ('address', models.TextField(blank=True, verbose_name='住所')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
            ],
            options={
                'verbose_name': '顧客',
                'verbose_name_plural': '顧客',
                'ordering': ['customer_id'],
            },
        ),
    ]
